---
- name: Add Mozilla Team PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa

- name: Configure APT pinning for Mozilla Team PPA
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/{{ mozilla_app }}
    content: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001

      Package: {{ mozilla_app }}
      Pin: version 2:1snap*
      Pin-Priority: -1

  loop: '{{ mozilla_apps }}'
  loop_control:
    loop_var: mozilla_app

- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Remove snap package
  become: true
  community.general.snap:
    name: '{{ mozilla_app }}'
    state: absent
  loop: '{{ mozilla_apps }}'
  loop_control:
    loop_var: mozilla_app
  failed_when: false

- name: Remove apt package
  become: true
  ansible.builtin.apt:
    name: '{{ mozilla_apps }}'
    state: absent
    autoremove: true

- name: Install {{ mozilla_apps }}
  become: true
  ansible.builtin.apt:
    name: '{{ mozilla_apps }}'
    state: present
